### ISSUE TITLE
bootstrap 

### ISSUE THREAD

**Issue by pscrusher101** [uttejh/Video-Tutorials#2]
need help with an error stating: glyphicons  images not found in bootstrap.

**Comment by uttejh** [comment]
Things to do:
- Download bootstrap .zip folder
- Place the bootstrap folder (Whole folder) parallel to index.html
- Now try: <link rel="stylesheet" href="bootstrap/css/bootstrap.css"> 
This should solve your problems
NOTE: Do not use CDN's
